#!/usr/bin/env python3
"""Build a "tom clock drift" demo: all three GHOST TOMS trigger lanes pass
through one shared delay before reaching the module, as if the toms were
being generated by a separate, slightly-unsynced drum machine (e.g. a Korg
whose clock has drifted against the main 909-style kit).

This is a simpler alternative to per-hit micro-timing (the Ableton-native
"Spastik" nudge trick, which has no real hardware equivalent and isn't what
this patch is going for): one uniform, shared delay for all three tom lanes,
not per-hit and not per-voice-independent. Not attributed to any specific
artist -- it's a general drum-machine-sync idea, not a recreation.

Signal path: Hora tom lanes (3 mono trigs) -> Fundamental Merge (3ch poly)
-> Bogaudio CVD (single TIME knob delays all 3 channels identically) ->
Fundamental Split (back to 3 mono trigs) -> Toms HIGH/MID/LOW trig inputs.

CVD's delay math (from source): delaySeconds = (TIME_PARAM / divisor) * 10,
divisor is 100/10/1 for TIME_SCALE_PARAM 0/1/2. TIME_PARAM=0.2,
TIME_SCALE_PARAM=0 (divisor 100) -> 0.2/100*10 = 0.02s = 20ms delay.
MIX_PARAM=1.0 (fully wet) so the on-grid dry trigger is replaced by the
delayed one, not layered with it (which would flam instead of drift).
"""
import os

import build_demos as D
import build_lessons as L

DEMODIR = os.path.join(L.REPO, "patches/demos")

MERGE_ID = 9400000000000001
CVD_ID = 9400000000000002
SPLIT_ID = 9400000000000003

# Fundamental (VCV Free) Merge/Split port ids.
MERGE_IN, MERGE_OUT = 0, 0          # MONO_INPUTS[0..], POLY_OUTPUT
SPLIT_IN, SPLIT_OUT = 0, 0          # POLY_INPUT, MONO_OUTPUTS[0..]
# Bogaudio CVD param/port ids.
CVD_TIME_PARAM, CVD_TIME_SCALE_PARAM, CVD_MIX_PARAM = 0, 1, 2
CVD_IN, CVD_OUT = 2, 0              # IN_INPUT is input 2; OUT_OUTPUT is output 0

PATTERN = {
    L.KICK_TRACK: D.bars([1, 5, 9, 13]),
    L.CHH_TRACK:  D.bars([1, 3, 5, 7, 9, 11, 13, 15]),
    L.TOM_LO_TRACK:  D.bars([1, 9]),
    L.TOM_MID_TRACK: D.bars([5, 13]),
    L.TOM_HI_TRACK:  D.bars([3, 7, 11, 15]),
    L.ACCENT_TRACK:  D.bars([1, 9]),
}


def add_drift_chain(data):
    data["modules"] += [
        dict(id=MERGE_ID, plugin="Fundamental", model="Merge",
             version="2.0.0", pos=[24, 3]),
        dict(id=CVD_ID, plugin="Bogaudio", model="Bogaudio-CVD",
             version="2.0.0", pos=[28, 3],
             params=[dict(id=CVD_TIME_PARAM, value=0.2),
                     dict(id=CVD_TIME_SCALE_PARAM, value=0.0),
                     dict(id=CVD_MIX_PARAM, value=1.0)]),
        dict(id=SPLIT_ID, plugin="Fundamental", model="Split",
             version="2.0.0", pos=[31, 3]),
    ]


def reroute_toms_through_drift(data):
    """Remove the direct Hora->Toms tom-trigger cables assemble_gmix made,
    replace with Hora -> Merge -> CVD -> Split -> Toms."""
    h = L.by_model(data, "Drumsequencer")["id"]
    t = L.by_model(data, "Toms")["id"]
    direct_ids = {L.TM_HI_TRIG, L.TM_MID_TRIG, L.TM_LO_TRIG}
    data["cables"] = [c for c in data["cables"]
                      if not (c["inputModuleId"] == t and c["inputId"] in direct_ids)]

    # Hora tom lanes -> Merge (channel order: HIGH, MID, LOW)
    L.cable(data, h, L.out_of(L.TOM_HI_TRACK),  MERGE_ID, MERGE_IN + 0, "#7a4ec2")
    L.cable(data, h, L.out_of(L.TOM_MID_TRACK), MERGE_ID, MERGE_IN + 1, "#7a4ec2")
    L.cable(data, h, L.out_of(L.TOM_LO_TRACK),  MERGE_ID, MERGE_IN + 2, "#7a4ec2")
    # Merge -> CVD -> Split
    L.cable(data, MERGE_ID, MERGE_OUT, CVD_ID, CVD_IN, "#268bd2")
    L.cable(data, CVD_ID, CVD_OUT, SPLIT_ID, SPLIT_IN, "#268bd2")
    # Split -> Toms trig inputs, same channel order as the Merge inputs above
    L.cable(data, SPLIT_ID, SPLIT_OUT + 0, t, L.TM_HI_TRIG,  "#7a4ec2")
    L.cable(data, SPLIT_ID, SPLIT_OUT + 1, t, L.TM_MID_TRIG, "#7a4ec2")
    L.cable(data, SPLIT_ID, SPLIT_OUT + 2, t, L.TM_LO_TRIG,  "#7a4ec2")


def build():
    data = L.load_base()
    L.drop_module(data, "Bogaudio-UMix")       # GHOST MIX replaces UMix
    L.add_toms(data)
    L.add_snr(data)
    L.add_chhohh(data)
    L.add_crashride(data)
    L.add_ghostmix(data)
    add_drift_chain(data)
    L.reset_routing(data)
    D.set_tempo(data, 126)
    L.assemble_gmix(data, PATTERN)
    reroute_toms_through_drift(data)
    L.save_vcv(data, os.path.join(DEMODIR, "toms-clock-drift.vcv"))


if __name__ == "__main__":
    os.makedirs(DEMODIR, exist_ok=True)
    build()
    print("toms-clock-drift: all three tom lanes uniformly delayed ~20ms "
          "via Merge -> Bogaudio CVD -> Split, simulating an unsynced "
          "second drum machine.")
